driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    command: /sbin/init
    pre_build_image: true
provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
  playbooks:
    converge: playbook.yml